### ISSUE TITLE
Got a non fatal error when Bastian signed up (see comment)

### ISSUE THREAD

**Issue by j-brower** [OSC-CSC480SP16/FamilyTree#6]
TypeError: Not a string or buffer
    at TypeError (native)
    at Cipher.update (crypto.js:140:26)
    at Object.module.exports.userSignup (/home/jbrower/Roots/Roots-engine-R1/api/controllers/LoginController.js:266:42)

**Comment by j-brower** [comment]
Can't replicate this in sign ups on current engine-debug.
